// TODO Create improved interpreter not generated by chatgpt
export default (code: string, input = "") => {
  const memory = new Uint8Array(30000); // Memory tape
  let pointer = 0; // Data pointer
  let inputIndex = 0; // Input pointer
  let output = ""; // Output string
  let loopStack = []; // Loop stack to manage brackets

  for (let i = 0; i < code.length; i++) {
    const command = code[i];

    switch (command) {
      case ">":
        pointer++;
        break;
      case "<":
        pointer--;
        break;
      case "+":
        memory[pointer]++;
        break;
      case "-":
        memory[pointer]--;
        break;
      case ".":
        output += String.fromCharCode(memory[pointer]);
        break;
      case ",":
        memory[pointer] = inputIndex < input.length ? input.charCodeAt(inputIndex++) : 0;
        break;
      case "[":
        if (memory[pointer] === 0) {
          let openBrackets = 1;
          while (openBrackets > 0) {
            i++;
            if (code[i] === "[") openBrackets++;
            if (code[i] === "]") openBrackets--;
          }
        } else {
          loopStack.push(i);
        }
        break;
      case "]":
        if (memory[pointer] !== 0) {
          i = loopStack[loopStack.length - 1];
        } else {
          loopStack.pop();
        }
        break;
      default:
        continue;
    }
  }

  return output;
};
